In [6]:
import pandas as pd
import numpy as np

In [10]:
credits = pd.read_csv("tmdb_5000_credits.csv")
movies = pd.read_csv("tmdb_5000_movies.csv")

In [11]:
credits.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  4803 non-null   int64
 1   title     4803 non-null   object
 2   cast      4803 non-null   object
 3   crew      4803 non-null   object
dtypes: int64(1), object(3)
memory usage: 150.2+ KB

In [12]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   object
 2   homepage              1712 non-null   object
 3   id                    4803 non-null   int64
 4   keywords              4803 non-null   object
 5   original_language     4803 non-null   object
 6   original_title        4803 non-null   object
 7   overview              4800 non-null   object
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   object
 10  production_countries  4803 non-null   object
 11  release_date          4802 non-null   object
 12  revenue               4803 non-null   int64
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   object
 15  status                4803 non-null   object
 16  tagline               3959 non-null   object
 17  title                 4803 non-null   object
 18  vote_average          4803 non-null   float64
 19  vote_count            4803 non-null   int64
dtypes: float64(3), int64(4), object(13)
memory usage: 750.6+ KB

In [14]:
credits=credits[['movie_id','cast','crew']]
movies=movies[['genres','id','keywords','overview','production_companies','tagline','title']]

In [15]:
credits

,movie_id,cast,crew
0,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...
4798,9367,"[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4799,72766,"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4800,231617,"[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4801,126186,"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4802,25975,"[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [16]:
df=pd.merge(credits,movies,left_on='movie_id',right_on='id',how='inner')

In [17]:
df

,movie_id,cast,crew,genres,id,keywords,overview,production_companies,tagline,title
0,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di...","[{""name"": ""Ingenious Film Partners"", ""id"": 289...",Enter the World of Pandora.,Avatar
1,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","Captain Barbossa, long believed to be dead, ha...","[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End
2,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",A cryptic message from Bond’s past sends him o...,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",A Plan No One Escapes,Spectre
3,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...","[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",Following the death of District Attorney Harve...,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",The Legend Ends,The Dark Knight Rises
4,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","John Carter is a war-weary, former military ca...","[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","Lost in our world, found in another.",John Carter
...,...,...,...,...,...,...,...,...,...,...
4798,9367,"[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de...","[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",9367,"[{""id"": 5616, ""name"": ""united states\u2013mexi...",El Mariachi just wants to play his guitar and ...,"[{""name"": ""Columbia Pictures"", ""id"": 5}]","He didn't come looking for trouble, but troubl...",El Mariachi
4799,72766,"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de...","[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",72766,[],A newlywed couple's honeymoon is upended by th...,[],A newlywed couple's honeymoon is upended by th...,Newlyweds
4800,231617,"[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de...","[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",231617,"[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...","""Signed, Sealed, Delivered"" introduces a dedic...","[{""name"": ""Front Street Pictures"", ""id"": 3958}...",NaN,"Signed, Sealed, Delivered"
4801,126186,"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de...",[],126186,[],When ambitious New York attorney Sam is sent t...,[],A New Yorker in Shanghai,Shanghai Calling
4802,25975,"[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de...","[{""id"": 99, ""name"": ""Documentary""}]",25975,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",Ever since the second grade when he first saw ...,"[{""name"": ""rusty bear entertainment"", ""id"": 87...",NaN,My Date with Drew

In [18]:
df.sample()

,movie_id,cast,crew,genres,id,keywords,overview,production_companies,tagline,title
437,11665,"[{""cast_id"": 4, ""character"": ""Maxwell Smart"", ...","[{""credit_id"": ""52fe44749251416c750355c1"", ""de...","[{""id"": 28, ""name"": ""Action""}, {""id"": 35, ""nam...",11665,"[{""id"": 246, ""name"": ""dancing""}, {""id"": 470, ""...",When the identities of secret agents from Cont...,"[{""name"": ""Village Roadshow Pictures"", ""id"": 7...",Saving The World...And Loving It!,Get Smart

In [19]:
df=df.drop(columns=['movie_id'])

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   cast                  4803 non-null   object
 1   crew                  4803 non-null   object
 2   genres                4803 non-null   object
 3   id                    4803 non-null   int64
 4   keywords              4803 non-null   object
 5   overview              4800 non-null   object
 6   production_companies  4803 non-null   object
 7   tagline               3959 non-null   object
 8   title                 4803 non-null   object
dtypes: int64(1), object(8)
memory usage: 337.8+ KB

In [21]:
desc=df.loc[0,'genres']

In [22]:
desc

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [23]:
import ast
names = []
x = ast.literal_eval(desc)
for item in x:
    names.append(item['name'])

comma_desc = ','.join(names)
comma_desc

'Action,Adventure,Fantasy,Science Fiction'

In [24]:
df.sample()

,cast,crew,genres,id,keywords,overview,production_companies,tagline,title
4645,"[{""cast_id"": 22, ""character"": ""Clive"", ""credit...","[{""credit_id"": ""52fe4acf9251416c750eeda3"", ""de...","[{""id"": 35, ""name"": ""Comedy""}]",142132,"[{""id"": 187056, ""name"": ""woman director""}]",Look at the lives of struggling L.A. scene roc...,"[{""name"": ""Channel Four Films"", ""id"": 181}, {""...",NaN,Sugar Town

In [25]:
#To create the funcation
import ast
def get_names(desc):
    names = []
    x = ast.literal_eval(desc)
    for item in x:
        names.append(item['name'])
    
    comma_desc = ','.join(names)
    return comma_desc

In [26]:
df['cast']=df['cast'].apply(get_names)
df['crew']=df['crew'].apply(get_names)
df['genres']=df['genres'].apply(get_names)
df['keywords']=df['keywords'].apply(get_names)
df['production_companies']=df['production_companies'].apply(get_names)

In [27]:
df.sample()

,cast,crew,genres,id,keywords,overview,production_companies,tagline,title
4473,"Sara Paxton,Pat Healy,Kelly McGillis,George Ri...","Larry Fessenden,Lisa Fields,Ti West,Ti West,Ti...","Horror,Thriller",58428,"anti terror,terror,beer,supernatural,towel,inn...",During the final days at the Yankee Pedlar Inn...,"Glass Eye Pix,Dark Sky Films",Some guests never checked out.,The Innkeepers

In [28]:
df['cast']=df['cast'].str.replace(' ','-')
df['crew']=df['crew'].str.replace(' ','-')
df['genres']=df['genres'].str.replace(' ','-')
df['keywords']=df['keywords'].str.replace(' ','-')
df['production_companies']=df['production_companies'].str.replace(' ','-')

In [29]:
df.sample()

,cast,crew,genres,id,keywords,overview,production_companies,tagline,title
4460,"Kevin-Pollak,Timothy-Hutton,Sheryl-Lee-Ralph,C...","Rod-Lurie,Rod-Lurie,Larry-Groupé,Marc-Frydman,...","Action,Drama,Mystery,Thriller",25212,"diner,judgment-call",The President of the United States must deal w...,"Battleplan-Productions,TF1-International,Moons...",NaN,Deterrence

In [30]:
df.fillna(" ",inplace=True)

In [31]:
df['tags']=df['genres']+','+df['keywords'] + ',' + df['tagline'] + ',' + df['overview'] + ',' + df['production_companies'] + ',' + df['cast'] + ',' + df['crew']

In [32]:
df

,cast,crew,genres,id,keywords,overview,production_companies,tagline,title,tags
0,"Sam-Worthington,Zoe-Saldana,Sigourney-Weaver,S...","Stephen-E.-Rivkin,Rick-Carter,Christopher-Boye...","Action,Adventure,Fantasy,Science-Fiction",19995,"culture-clash,future,space-war,space-colony,so...","In the 22nd century, a paraplegic Marine is di...","Ingenious-Film-Partners,Twentieth-Century-Fox-...",Enter the World of Pandora.,Avatar,"Action,Adventure,Fantasy,Science-Fiction,cultu..."
1,"Johnny-Depp,Orlando-Bloom,Keira-Knightley,Stel...","Dariusz-Wolski,Gore-Verbinski,Jerry-Bruckheime...","Adventure,Fantasy,Action",285,"ocean,drug-abuse,exotic-island,east-india-trad...","Captain Barbossa, long believed to be dead, ha...","Walt-Disney-Pictures,Jerry-Bruckheimer-Films,S...","At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,"Adventure,Fantasy,Action,ocean,drug-abuse,exot..."
2,"Daniel-Craig,Christoph-Waltz,Léa-Seydoux,Ralph...","Thomas-Newman,Sam-Mendes,Anna-Pinnock,John-Log...","Action,Adventure,Crime",206647,"spy,based-on-novel,secret-agent,sequel,mi6,bri...",A cryptic message from Bond’s past sends him o...,"Columbia-Pictures,Danjaq,B24",A Plan No One Escapes,Spectre,"Action,Adventure,Crime,spy,based-on-novel,secr..."
3,"Christian-Bale,Michael-Caine,Gary-Oldman,Anne-...","Hans-Zimmer,Charles-Roven,Christopher-Nolan,Ch...","Action,Crime,Drama,Thriller",49026,"dc-comics,crime-fighter,terrorist,secret-ident...",Following the death of District Attorney Harve...,"Legendary-Pictures,Warner-Bros.,DC-Entertainme...",The Legend Ends,The Dark Knight Rises,"Action,Crime,Drama,Thriller,dc-comics,crime-fi..."
4,"Taylor-Kitsch,Lynn-Collins,Samantha-Morton,Wil...","Andrew-Stanton,Andrew-Stanton,John-Lasseter,Co...","Action,Adventure,Science-Fiction",49529,"based-on-novel,mars,medallion,space-travel,pri...","John Carter is a war-weary, former military ca...",Walt-Disney-Pictures,"Lost in our world, found in another.",John Carter,"Action,Adventure,Science-Fiction,based-on-nove..."
...,...,...,...,...,...,...,...,...,...,...
4798,"Carlos-Gallardo,Jaime-de-Hoyos,Peter-Marquardt...","Robert-Rodriguez,Robert-Rodriguez,Robert-Rodri...","Action,Crime,Thriller",9367,"united-states–mexico-barrier,legs,arms,paper-k...",El Mariachi just wants to play his guitar and ...,Columbia-Pictures,"He didn't come looking for trouble, but troubl...",El Mariachi,"Action,Crime,Thriller,united-states–mexico-bar..."
4799,"Edward-Burns,Kerry-Bishé,Marsha-Dietlein,Caitl...","Edward-Burns,Edward-Burns,Edward-Burns,William...","Comedy,Romance",72766,,A newlywed couple's honeymoon is upended by th...,,A newlywed couple's honeymoon is upended by th...,Newlyweds,"Comedy,Romance,,A newlywed couple's honeymoon ..."
4800,"Eric-Mabius,Kristin-Booth,Crystal-Lowe,Geoff-G...","Carla-Hetland,Harvey-Kahn,Adam-Sliwinski,Marth...","Comedy,Drama,Romance,TV-Movie",231617,"date,love-at-first-sight,narration,investigati...","""Signed, Sealed, Delivered"" introduces a dedic...","Front-Street-Pictures,Muse-Entertainment-Enter...",,"Signed, Sealed, Delivered","Comedy,Drama,Romance,TV-Movie,date,love-at-fir..."
4801,"Daniel-Henney,Eliza-Coupe,Bill-Paxton,Alan-Ruc...","Daniel-Hsia,Daniel-Hsia",,126186,,When ambitious New York attorney Sam is sent t...,,A New Yorker in Shanghai,Shanghai Calling,",,A New Yorker in Shanghai,When ambitious New ..."
4802,"Drew-Barrymore,Brian-Herzlinger,Corey-Feldman,...","Clark-Peterson,Andrew-Reimer,Brian-Herzlinger,...",Documentary,25975,"obsession,camcorder,crush,dream-girl",Ever since the second grade when he first saw ...,"rusty-bear-entertainment,lucky-crow-films",,My Date with Drew,"Documentary,obsession,camcorder,crush,dream-gi..."

In [33]:
df = df[['id', 'title', 'tags']]

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      4803 non-null   int64
 1   title   4803 non-null   object
 2   tags    4803 non-null   object
dtypes: int64(1), object(2)
memory usage: 112.7+ KB

In [35]:
df['tags']=df['tags'].str.lower()

C:\Users\Tukaram\AppData\Local\Temp\ipykernel_16096\1464131415.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['tags']=df['tags'].str.lower()

In [36]:
df.loc[0,'tags']

"action,adventure,fantasy,science-fiction,culture-clash,future,space-war,space-colony,society,space-travel,futuristic,romance,space,alien,tribe,alien-planet,cgi,marine,soldier,battle,love-affair,anti-war,power-relations,mind-and-soul,3d,enter the world of pandora.,in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.,ingenious-film-partners,twentieth-century-fox-film-corporation,dune-entertainment,lightstorm-entertainment,sam-worthington,zoe-saldana,sigourney-weaver,stephen-lang,michelle-rodriguez,giovanni-ribisi,joel-david-moore,cch-pounder,wes-studi,laz-alonso,dileep-rao,matt-gerald,sean-anthony-moran,jason-whyte,scott-lawrence,kelly-kilgour,james-patrick-pitt,sean-patrick-murphy,peter-dillon,kevin-dorman,kelson-henderson,david-van-horn,jacob-tomuri,michael-blain-rozgay,jon-curry,luke-hawker,woody-schultz,peter-mensah,sonia-yee,jahnel-curfman,ilram-choi,kyla-warren,lisa-roumain,debra-wilson,chris-mala,taylor-kibby,jodie-landau,julie-lamm,cullen-b.-madden,joseph-brady-madden,frankie-torres,austin-wilson,sara-wilson,tamica-washington-miller,lucy-briant,nathan-meister,gerry-blair,matthew-chamberlain,paul-yates,wray-wilson,james-gaylyn,melvin-leno-clark-iii,carvon-futrell,brandon-jelkes,micah-moch,hanniyah-muhammad,christopher-nolen,christa-oliver,april-marie-thomas,bravita-a.-threatt,colin-bleasdale,mike-bodnar,matt-clayton,nicole-dionne,jamie-harrison,allan-henry,anthony-ingruber,ashley-jeffery,dean-knowsley,joseph-mika-hunt,terry-notary,kai-pantano,logan-pithyou,stuart-pollock,raja,gareth-ruck,rhian-sheehan,t.-j.-storm,jodie-taylor,alicia-vela-bailey,richard-whiteside,nikie-zambo,julene-renee,stephen-e.-rivkin,rick-carter,christopher-boyes,christopher-boyes,mali-finn,james-horner,james-cameron,james-cameron,james-cameron,james-cameron,james-cameron,andrew-menzies,jill-brooks,margery-simkin,kevin-ishioka,dick-bernstein,shannon-mills,dennie-thorpe,jana-vance,deborah-lynn-scott,jon-landau,sean-haworth,kim-sinclair,kim-sinclair,richard-f.-mays,laeta-kalogridis,mayes-c.-rubeo,mauro-fiore,scott-herbertson,woody-schultz,linda-devetta,linda-devetta,richard-bluck,simon-bright,richard-martin,steve-r.-moore,john-refoua,karl-j.-martin,chiling-lin,ilram-choi,steven-quale,carla-meyer,nick-bassett,jill-cormack,andy-mclaren,terry-notary,garrett-warren,jonathan-rothbart,stefan-dechant,todd-cherniawsky,miranda-rivers,robert-stromberg,john-harding,roberto-de-angelis,mike-smithson,alain-lalanne,lucas-salton,janace-tashjian,stephen-rosenbaum,frankie-karena,lisa-lovaas,jonathan-fawkner,robert-bavin,anthony-almaraz,carolyn-m.-fenton,beth-koenigsberg,sam-page,tex-kadonaga,kim-foscato,tammy-s.-lee,denny-caira,james-waitkus,addison-teague,c.-scott-baker,luke-caska,david-chow,jonathan-dyer,joseph-hiura,rebecca-jellie,robert-andrew-johnson,mike-stassi,john-villarino,jeffrey-wisniewski,cheryl-nardi,marshall-winn,gwendolyn-yates-whittle,william-stein,lula-washington,chris-del-conte,r.-christopher-white,dan-lemmon,tim-nielsen,michael-mulholland,thomas-nittmann,edson-williams,christine-carr,john-bruno,david-emmerichs,christopher-scarabosio,jennifer-teves,brigitte-yorke,ken-fischer,iain-hutton,steve-ingram,joyce-cox,jenny-foster,christopher-marino,jim-milton,cyndi-ochs,lucas-putnam,anthony-'max'-ivins,john-knoll,eric-saindon,wayne-stables,david-stinnett,guy-williams,stuart-thorp,giles-coburn,mark-fellman,scott-sprague,jeremy-hollobon,orlando-meunier,taisuke-tanimura,lilia-mishel-acevedo,alejandro-m.-hernandez,marvin-hall,judy-alley,mike-perry,andrew-morley,seth-engstrom,eric-oliver,matsune-suzuki,paul-tobin,roxane-griffin,arun-ram-mohan,georgia-lockhart-adams,thrain-shadbolt,brad-alexander,shadi-almassizadeh,simon-clutterbuck,graeme-demmocks,adrian-fernandes,mitch-gates,jerry-kung,andy-lomas,sebastian-marino,matthias-menz,sergei-nevshupov,philippe-rebours,michael-takarangi,david-weitzberg,ben-white,min-windle"